name = "cloudiator"
compatibility_date = "2026-08-28"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "bpbkv"
id = "3d8e2d56ff9a43769a2c89f23db176dd"
