name = "cloudiator"
main = "web/src/index.ts"
compatibility_date = "2026-08-28"
workers_dev = true
keep_vars = true

[assets]
directory = "web/assets"
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "bpbkv"
id = "3d8e2d56ff9a43769a2c89f23db176dd"
